// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/f00b455/blank-go/pkg/stocks"
	"github.com/stretchr/testify/mock"
)

// MockStocksClient is a mock type for the StocksClient interface
type MockStocksClient struct {
	mock.Mock
}

// GetQuote provides a mock function with given fields: ticker
func (m *MockStocksClient) GetQuote(ticker string) (*stocks.YahooQuote, error) {
	ret := m.Called(ticker)

	var r0 *stocks.YahooQuote
	if rf, ok := ret.Get(0).(func(string) *stocks.YahooQuote); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stocks.YahooQuote)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuotes provides a mock function with given fields: tickers
func (m *MockStocksClient) GetQuotes(tickers []string) (map[string]*stocks.YahooQuote, error) {
	ret := m.Called(tickers)

	var r0 map[string]*stocks.YahooQuote
	if rf, ok := ret.Get(0).(func([]string) map[string]*stocks.YahooQuote); ok {
		r0 = rf(tickers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*stocks.YahooQuote)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(tickers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
