all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/f00b455/blank-go/pkg/task:
    interfaces:
      Repository:
  github.com/f00b455/blank-go/pkg/weather:
    interfaces:
      WeatherClient:
      HTTPClient:
  github.com/f00b455/blank-go/pkg/dax:
    interfaces:
      Repository:
  github.com/f00b455/blank-go/pkg/stocks:
    interfaces:
      StocksClient:
  github.com/f00b455/blank-go/internal/handlers:
    interfaces:
      WeatherService:
      StocksService:
