// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/f00b455/blank-go/pkg/dax"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BulkUpsert provides a mock function for the type MockRepository
func (_mock *MockRepository) BulkUpsert(records []dax.DAXRecord) error {
	ret := _mock.Called(records)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]dax.DAXRecord) error); ok {
		r0 = returnFunc(records)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type MockRepository_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - records []dax.DAXRecord
func (_e *MockRepository_Expecter) BulkUpsert(records interface{}) *MockRepository_BulkUpsert_Call {
	return &MockRepository_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", records)}
}

func (_c *MockRepository_BulkUpsert_Call) Run(run func(records []dax.DAXRecord)) *MockRepository_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dax.DAXRecord
		if args[0] != nil {
			arg0 = args[0].([]dax.DAXRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_BulkUpsert_Call) Return(err error) *MockRepository_BulkUpsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_BulkUpsert_Call) RunAndReturn(run func(records []dax.DAXRecord) error) *MockRepository_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockRepository
func (_mock *MockRepository) Count() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Count() *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockRepository_Count_Call) Run(run func()) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(n int, err error) *MockRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func() (int, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(record *dax.DAXRecord) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*dax.DAXRecord) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - record *dax.DAXRecord
func (_e *MockRepository_Expecter) Create(record interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", record)}
}

func (_c *MockRepository_Create_Call) Run(run func(record *dax.DAXRecord)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dax.DAXRecord
		if args[0] != nil {
			arg0 = args[0].(*dax.DAXRecord)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(record *dax.DAXRecord) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) DeleteAll() *MockRepository_DeleteAll_Call {
	return &MockRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll")}
}

func (_c *MockRepository_DeleteAll_Call) Run(run func()) *MockRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_DeleteAll_Call) Return(err error) *MockRepository_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteAll_Call) RunAndReturn(run func() error) *MockRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAll(page int, limit int) ([]dax.DAXRecord, int, error) {
	ret := _mock.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dax.DAXRecord
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]dax.DAXRecord, int, error)); ok {
		return returnFunc(page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []dax.DAXRecord); ok {
		r0 = returnFunc(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dax.DAXRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = returnFunc(page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = returnFunc(page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - page int
//   - limit int
func (_e *MockRepository_Expecter) FindAll(page interface{}, limit interface{}) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", page, limit)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(page int, limit int)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(dAXRecords []dax.DAXRecord, n int, err error) *MockRepository_FindAll_Call {
	_c.Call.Return(dAXRecords, n, err)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(page int, limit int) ([]dax.DAXRecord, int, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFilters provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByFilters(ticker string, year *int, page int, limit int) ([]dax.DAXRecord, int, error) {
	ret := _mock.Called(ticker, year, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilters")
	}

	var r0 []dax.DAXRecord
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, *int, int, int) ([]dax.DAXRecord, int, error)); ok {
		return returnFunc(ticker, year, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int, int, int) []dax.DAXRecord); ok {
		r0 = returnFunc(ticker, year, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dax.DAXRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int, int, int) int); ok {
		r1 = returnFunc(ticker, year, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, *int, int, int) error); ok {
		r2 = returnFunc(ticker, year, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_FindByFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFilters'
type MockRepository_FindByFilters_Call struct {
	*mock.Call
}

// FindByFilters is a helper method to define mock.On call
//   - ticker string
//   - year *int
//   - page int
//   - limit int
func (_e *MockRepository_Expecter) FindByFilters(ticker interface{}, year interface{}, page interface{}, limit interface{}) *MockRepository_FindByFilters_Call {
	return &MockRepository_FindByFilters_Call{Call: _e.mock.On("FindByFilters", ticker, year, page, limit)}
}

func (_c *MockRepository_FindByFilters_Call) Run(run func(ticker string, year *int, page int, limit int)) *MockRepository_FindByFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_FindByFilters_Call) Return(dAXRecords []dax.DAXRecord, n int, err error) *MockRepository_FindByFilters_Call {
	_c.Call.Return(dAXRecords, n, err)
	return _c
}

func (_c *MockRepository_FindByFilters_Call) RunAndReturn(run func(ticker string, year *int, page int, limit int) ([]dax.DAXRecord, int, error)) *MockRepository_FindByFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function for the type MockRepository
func (_mock *MockRepository) GetMetrics(ticker string) ([]string, error) {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockRepository_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ticker string
func (_e *MockRepository_Expecter) GetMetrics(ticker interface{}) *MockRepository_GetMetrics_Call {
	return &MockRepository_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ticker)}
}

func (_c *MockRepository_GetMetrics_Call) Run(run func(ticker string)) *MockRepository_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetMetrics_Call) Return(strings []string, err error) *MockRepository_GetMetrics_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepository_GetMetrics_Call) RunAndReturn(run func(ticker string) ([]string, error)) *MockRepository_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}
