// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dax "github.com/f00b455/blank-go/pkg/dax"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BulkUpsert provides a mock function with given fields: records
func (_m *MockRepository) BulkUpsert(records []dax.DAXRecord) error {
	ret := _m.Called(records)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]dax.DAXRecord) error); ok {
		r0 = rf(records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type MockRepository_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - records []dax.DAXRecord
func (_e *MockRepository_Expecter) BulkUpsert(records interface{}) *MockRepository_BulkUpsert_Call {
	return &MockRepository_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", records)}
}

func (_c *MockRepository_BulkUpsert_Call) Run(run func(records []dax.DAXRecord)) *MockRepository_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]dax.DAXRecord))
	})
	return _c
}

func (_c *MockRepository_BulkUpsert_Call) Return(_a0 error) *MockRepository_BulkUpsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_BulkUpsert_Call) RunAndReturn(run func([]dax.DAXRecord) error) *MockRepository_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with no fields
func (_m *MockRepository) Count() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Count() *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockRepository_Count_Call) Run(run func()) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(_a0 int, _a1 error) *MockRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func() (int, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: record
func (_m *MockRepository) Create(record *dax.DAXRecord) error {
	ret := _m.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dax.DAXRecord) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - record *dax.DAXRecord
func (_e *MockRepository_Expecter) Create(record interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", record)}
}

func (_c *MockRepository_Create_Call) Run(run func(record *dax.DAXRecord)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dax.DAXRecord))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(*dax.DAXRecord) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function with no fields
func (_m *MockRepository) DeleteAll() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
func (_e *MockRepository_Expecter) DeleteAll() *MockRepository_DeleteAll_Call {
	return &MockRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll")}
}

func (_c *MockRepository_DeleteAll_Call) Run(run func()) *MockRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_DeleteAll_Call) Return(_a0 error) *MockRepository_DeleteAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteAll_Call) RunAndReturn(run func() error) *MockRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: page, limit
func (_m *MockRepository) FindAll(page int, limit int) ([]dax.DAXRecord, int, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dax.DAXRecord
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]dax.DAXRecord, int, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []dax.DAXRecord); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dax.DAXRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - page int
//   - limit int
func (_e *MockRepository_Expecter) FindAll(page interface{}, limit interface{}) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", page, limit)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(page int, limit int)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(_a0 []dax.DAXRecord, _a1 int, _a2 error) *MockRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(int, int) ([]dax.DAXRecord, int, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByFilters provides a mock function with given fields: ticker, year, page, limit
func (_m *MockRepository) FindByFilters(ticker string, year *int, page int, limit int) ([]dax.DAXRecord, int, error) {
	ret := _m.Called(ticker, year, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilters")
	}

	var r0 []dax.DAXRecord
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *int, int, int) ([]dax.DAXRecord, int, error)); ok {
		return rf(ticker, year, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, *int, int, int) []dax.DAXRecord); ok {
		r0 = rf(ticker, year, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dax.DAXRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *int, int, int) int); ok {
		r1 = rf(ticker, year, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, *int, int, int) error); ok {
		r2 = rf(ticker, year, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_FindByFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFilters'
type MockRepository_FindByFilters_Call struct {
	*mock.Call
}

// FindByFilters is a helper method to define mock.On call
//   - ticker string
//   - year *int
//   - page int
//   - limit int
func (_e *MockRepository_Expecter) FindByFilters(ticker interface{}, year interface{}, page interface{}, limit interface{}) *MockRepository_FindByFilters_Call {
	return &MockRepository_FindByFilters_Call{Call: _e.mock.On("FindByFilters", ticker, year, page, limit)}
}

func (_c *MockRepository_FindByFilters_Call) Run(run func(ticker string, year *int, page int, limit int)) *MockRepository_FindByFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_FindByFilters_Call) Return(_a0 []dax.DAXRecord, _a1 int, _a2 error) *MockRepository_FindByFilters_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_FindByFilters_Call) RunAndReturn(run func(string, *int, int, int) ([]dax.DAXRecord, int, error)) *MockRepository_FindByFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function with given fields: ticker
func (_m *MockRepository) GetMetrics(ticker string) ([]string, error) {
	ret := _m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(ticker)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockRepository_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
//   - ticker string
func (_e *MockRepository_Expecter) GetMetrics(ticker interface{}) *MockRepository_GetMetrics_Call {
	return &MockRepository_GetMetrics_Call{Call: _e.mock.On("GetMetrics", ticker)}
}

func (_c *MockRepository_GetMetrics_Call) Run(run func(ticker string)) *MockRepository_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRepository_GetMetrics_Call) Return(_a0 []string, _a1 error) *MockRepository_GetMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMetrics_Call) RunAndReturn(run func(string) ([]string, error)) *MockRepository_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
