// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/f00b455/blank-go/pkg/dax"
	"github.com/stretchr/testify/mock"
)

// MockRepository is a mock type for the Repository interface
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: record
func (m *MockRepository) Create(record *dax.DAXRecord) error {
	ret := m.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dax.DAXRecord) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkUpsert provides a mock function with given fields: records
func (m *MockRepository) BulkUpsert(records []dax.DAXRecord) error {
	ret := m.Called(records)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]dax.DAXRecord) error); ok {
		r0 = rf(records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, limit
func (m *MockRepository) FindAll(page, limit int) ([]dax.DAXRecord, int, error) {
	ret := m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []dax.DAXRecord
	var r1 int
	var r2 error

	if rf, ok := ret.Get(0).(func(int, int) ([]dax.DAXRecord, int, error)); ok {
		return rf(page, limit)
	}

	if rf, ok := ret.Get(0).(func(int, int) []dax.DAXRecord); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dax.DAXRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByFilters provides a mock function with given fields: ticker, year, page, limit
func (m *MockRepository) FindByFilters(ticker string, year *int, page, limit int) ([]dax.DAXRecord, int, error) {
	ret := m.Called(ticker, year, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilters")
	}

	var r0 []dax.DAXRecord
	var r1 int
	var r2 error

	if rf, ok := ret.Get(0).(func(string, *int, int, int) ([]dax.DAXRecord, int, error)); ok {
		return rf(ticker, year, page, limit)
	}

	if rf, ok := ret.Get(0).(func(string, *int, int, int) []dax.DAXRecord); ok {
		r0 = rf(ticker, year, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dax.DAXRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *int, int, int) int); ok {
		r1 = rf(ticker, year, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, *int, int, int) error); ok {
		r2 = rf(ticker, year, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetMetrics provides a mock function with given fields: ticker
func (m *MockRepository) GetMetrics(ticker string) ([]string, error) {
	ret := m.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 []string
	var r1 error

	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(ticker)
	}

	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAll provides a mock function with no fields
func (m *MockRepository) DeleteAll() error {
	ret := m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with no fields
func (m *MockRepository) Count() (int, error) {
	ret := m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error

	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}

	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
