// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	weather "github.com/f00b455/blank-go/pkg/weather"
	mock "github.com/stretchr/testify/mock"
)

// MockWeatherClient is an autogenerated mock type for the WeatherClient type
type MockWeatherClient struct {
	mock.Mock
}

type MockWeatherClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherClient) EXPECT() *MockWeatherClient_Expecter {
	return &MockWeatherClient_Expecter{mock: &_m.Mock}
}

// GeocodeCity provides a mock function with given fields: cityName
func (_m *MockWeatherClient) GeocodeCity(cityName string) (*weather.GeocodingResult, error) {
	ret := _m.Called(cityName)

	if len(ret) == 0 {
		panic("no return value specified for GeocodeCity")
	}

	var r0 *weather.GeocodingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*weather.GeocodingResult, error)); ok {
		return rf(cityName)
	}
	if rf, ok := ret.Get(0).(func(string) *weather.GeocodingResult); ok {
		r0 = rf(cityName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.GeocodingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cityName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWeatherClient_GeocodeCity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeocodeCity'
type MockWeatherClient_GeocodeCity_Call struct {
	*mock.Call
}

// GeocodeCity is a helper method to define mock.On call
//   - cityName string
func (_e *MockWeatherClient_Expecter) GeocodeCity(cityName interface{}) *MockWeatherClient_GeocodeCity_Call {
	return &MockWeatherClient_GeocodeCity_Call{Call: _e.mock.On("GeocodeCity", cityName)}
}

func (_c *MockWeatherClient_GeocodeCity_Call) Run(run func(cityName string)) *MockWeatherClient_GeocodeCity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWeatherClient_GeocodeCity_Call) Return(_a0 *weather.GeocodingResult, _a1 error) *MockWeatherClient_GeocodeCity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWeatherClient_GeocodeCity_Call) RunAndReturn(run func(string) (*weather.GeocodingResult, error)) *MockWeatherClient_GeocodeCity_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentWeather provides a mock function with given fields: lat, lon
func (_m *MockWeatherClient) GetCurrentWeather(lat float64, lon float64) (*weather.WeatherResponse, error) {
	ret := _m.Called(lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWeather")
	}

	var r0 *weather.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, float64) (*weather.WeatherResponse, error)); ok {
		return rf(lat, lon)
	}
	if rf, ok := ret.Get(0).(func(float64, float64) *weather.WeatherResponse); ok {
		r0 = rf(lat, lon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(float64, float64) error); ok {
		r1 = rf(lat, lon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWeatherClient_GetCurrentWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWeather'
type MockWeatherClient_GetCurrentWeather_Call struct {
	*mock.Call
}

// GetCurrentWeather is a helper method to define mock.On call
//   - lat float64
//   - lon float64
func (_e *MockWeatherClient_Expecter) GetCurrentWeather(lat interface{}, lon interface{}) *MockWeatherClient_GetCurrentWeather_Call {
	return &MockWeatherClient_GetCurrentWeather_Call{Call: _e.mock.On("GetCurrentWeather", lat, lon)}
}

func (_c *MockWeatherClient_GetCurrentWeather_Call) Run(run func(lat float64, lon float64)) *MockWeatherClient_GetCurrentWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(float64))
	})
	return _c
}

func (_c *MockWeatherClient_GetCurrentWeather_Call) Return(_a0 *weather.WeatherResponse, _a1 error) *MockWeatherClient_GetCurrentWeather_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWeatherClient_GetCurrentWeather_Call) RunAndReturn(run func(float64, float64) (*weather.WeatherResponse, error)) *MockWeatherClient_GetCurrentWeather_Call {
	_c.Call.Return(run)
	return _c
}

// GetForecast provides a mock function with given fields: lat, lon, days
func (_m *MockWeatherClient) GetForecast(lat float64, lon float64, days int) (*weather.ForecastResponse, error) {
	ret := _m.Called(lat, lon, days)

	if len(ret) == 0 {
		panic("no return value specified for GetForecast")
	}

	var r0 *weather.ForecastResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, float64, int) (*weather.ForecastResponse, error)); ok {
		return rf(lat, lon, days)
	}
	if rf, ok := ret.Get(0).(func(float64, float64, int) *weather.ForecastResponse); ok {
		r0 = rf(lat, lon, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.ForecastResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(float64, float64, int) error); ok {
		r1 = rf(lat, lon, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWeatherClient_GetForecast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForecast'
type MockWeatherClient_GetForecast_Call struct {
	*mock.Call
}

// GetForecast is a helper method to define mock.On call
//   - lat float64
//   - lon float64
//   - days int
func (_e *MockWeatherClient_Expecter) GetForecast(lat interface{}, lon interface{}, days interface{}) *MockWeatherClient_GetForecast_Call {
	return &MockWeatherClient_GetForecast_Call{Call: _e.mock.On("GetForecast", lat, lon, days)}
}

func (_c *MockWeatherClient_GetForecast_Call) Run(run func(lat float64, lon float64, days int)) *MockWeatherClient_GetForecast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(float64), args[2].(int))
	})
	return _c
}

func (_c *MockWeatherClient_GetForecast_Call) Return(_a0 *weather.ForecastResponse, _a1 error) *MockWeatherClient_GetForecast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWeatherClient_GetForecast_Call) RunAndReturn(run func(float64, float64, int) (*weather.ForecastResponse, error)) *MockWeatherClient_GetForecast_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWeatherClient creates a new instance of MockWeatherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherClient {
	mock := &MockWeatherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
