// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/f00b455/blank-go/pkg/weather"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWeatherService creates a new instance of MockWeatherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherService {
	mock := &MockWeatherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWeatherService is an autogenerated mock type for the WeatherService type
type MockWeatherService struct {
	mock.Mock
}

type MockWeatherService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherService) EXPECT() *MockWeatherService_Expecter {
	return &MockWeatherService_Expecter{mock: &_m.Mock}
}

// GetCurrentWeatherByCoords provides a mock function for the type MockWeatherService
func (_mock *MockWeatherService) GetCurrentWeatherByCoords(lat string, lon string) (*weather.WeatherResponse, error) {
	ret := _mock.Called(lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWeatherByCoords")
	}

	var r0 *weather.WeatherResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*weather.WeatherResponse, error)); ok {
		return returnFunc(lat, lon)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *weather.WeatherResponse); ok {
		r0 = returnFunc(lat, lon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.WeatherResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(lat, lon)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherService_GetCurrentWeatherByCoords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWeatherByCoords'
type MockWeatherService_GetCurrentWeatherByCoords_Call struct {
	*mock.Call
}

// GetCurrentWeatherByCoords is a helper method to define mock.On call
//   - lat string
//   - lon string
func (_e *MockWeatherService_Expecter) GetCurrentWeatherByCoords(lat interface{}, lon interface{}) *MockWeatherService_GetCurrentWeatherByCoords_Call {
	return &MockWeatherService_GetCurrentWeatherByCoords_Call{Call: _e.mock.On("GetCurrentWeatherByCoords", lat, lon)}
}

func (_c *MockWeatherService_GetCurrentWeatherByCoords_Call) Run(run func(lat string, lon string)) *MockWeatherService_GetCurrentWeatherByCoords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWeatherService_GetCurrentWeatherByCoords_Call) Return(weatherResponse *weather.WeatherResponse, err error) *MockWeatherService_GetCurrentWeatherByCoords_Call {
	_c.Call.Return(weatherResponse, err)
	return _c
}

func (_c *MockWeatherService_GetCurrentWeatherByCoords_Call) RunAndReturn(run func(lat string, lon string) (*weather.WeatherResponse, error)) *MockWeatherService_GetCurrentWeatherByCoords_Call {
	_c.Call.Return(run)
	return _c
}

// GetForecastByCoords provides a mock function for the type MockWeatherService
func (_mock *MockWeatherService) GetForecastByCoords(lat string, lon string, days int) (*weather.ForecastResponse, error) {
	ret := _mock.Called(lat, lon, days)

	if len(ret) == 0 {
		panic("no return value specified for GetForecastByCoords")
	}

	var r0 *weather.ForecastResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int) (*weather.ForecastResponse, error)); ok {
		return returnFunc(lat, lon, days)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int) *weather.ForecastResponse); ok {
		r0 = returnFunc(lat, lon, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.ForecastResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = returnFunc(lat, lon, days)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherService_GetForecastByCoords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForecastByCoords'
type MockWeatherService_GetForecastByCoords_Call struct {
	*mock.Call
}

// GetForecastByCoords is a helper method to define mock.On call
//   - lat string
//   - lon string
//   - days int
func (_e *MockWeatherService_Expecter) GetForecastByCoords(lat interface{}, lon interface{}, days interface{}) *MockWeatherService_GetForecastByCoords_Call {
	return &MockWeatherService_GetForecastByCoords_Call{Call: _e.mock.On("GetForecastByCoords", lat, lon, days)}
}

func (_c *MockWeatherService_GetForecastByCoords_Call) Run(run func(lat string, lon string, days int)) *MockWeatherService_GetForecastByCoords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWeatherService_GetForecastByCoords_Call) Return(forecastResponse *weather.ForecastResponse, err error) *MockWeatherService_GetForecastByCoords_Call {
	_c.Call.Return(forecastResponse, err)
	return _c
}

func (_c *MockWeatherService_GetForecastByCoords_Call) RunAndReturn(run func(lat string, lon string, days int) (*weather.ForecastResponse, error)) *MockWeatherService_GetForecastByCoords_Call {
	_c.Call.Return(run)
	return _c
}

// GetWeatherByCity provides a mock function for the type MockWeatherService
func (_mock *MockWeatherService) GetWeatherByCity(cityName string) (*weather.WeatherResponse, error) {
	ret := _mock.Called(cityName)

	if len(ret) == 0 {
		panic("no return value specified for GetWeatherByCity")
	}

	var r0 *weather.WeatherResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*weather.WeatherResponse, error)); ok {
		return returnFunc(cityName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *weather.WeatherResponse); ok {
		r0 = returnFunc(cityName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*weather.WeatherResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cityName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWeatherService_GetWeatherByCity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeatherByCity'
type MockWeatherService_GetWeatherByCity_Call struct {
	*mock.Call
}

// GetWeatherByCity is a helper method to define mock.On call
//   - cityName string
func (_e *MockWeatherService_Expecter) GetWeatherByCity(cityName interface{}) *MockWeatherService_GetWeatherByCity_Call {
	return &MockWeatherService_GetWeatherByCity_Call{Call: _e.mock.On("GetWeatherByCity", cityName)}
}

func (_c *MockWeatherService_GetWeatherByCity_Call) Run(run func(cityName string)) *MockWeatherService_GetWeatherByCity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWeatherService_GetWeatherByCity_Call) Return(weatherResponse *weather.WeatherResponse, err error) *MockWeatherService_GetWeatherByCity_Call {
	_c.Call.Return(weatherResponse, err)
	return _c
}

func (_c *MockWeatherService_GetWeatherByCity_Call) RunAndReturn(run func(cityName string) (*weather.WeatherResponse, error)) *MockWeatherService_GetWeatherByCity_Call {
	_c.Call.Return(run)
	return _c
}
