// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/f00b455/blank-go/pkg/stocks"
	"github.com/stretchr/testify/mock"
)

// MockStocksService is a mock type for the StocksService interface
type MockStocksService struct {
	mock.Mock
}

// GetSummary provides a mock function with given fields: ticker
func (m *MockStocksService) GetSummary(ticker string) (*stocks.StockSummary, error) {
	ret := m.Called(ticker)

	var r0 *stocks.StockSummary
	if rf, ok := ret.Get(0).(func(string) *stocks.StockSummary); ok {
		r0 = rf(ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stocks.StockSummary)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ticker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBatchSummary provides a mock function with given fields: tickers
func (m *MockStocksService) GetBatchSummary(tickers string) (*stocks.BatchResponse, error) {
	ret := m.Called(tickers)

	var r0 *stocks.BatchResponse
	if rf, ok := ret.Get(0).(func(string) *stocks.BatchResponse); ok {
		r0 = rf(tickers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stocks.BatchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tickers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
